version: "3.7"

services:

  app:
    build: './app'
    container_name: 'app'
    ports:
      - "8000:8000"
    volumes:
      - type: 'bind'
        source: './volumes/project'
        target: '/app' 
  # nginx:
  #   build: './nginx'
  #   container_name: 'nginx'
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - type: 'bind'
  #       source: './volumes/media'
  #       target: '/app/media'
  #     - type: 'bind'
  #       source: './volumes/static'
  #       target: '/app/static'

